export default {
    home: {
        UPDATE_DATA_REQUESTED: 'UPDATE_DATA_REQUESTED',
        UPDATE_DATA_FAILURE: 'UPDATE_DATA_FAILURE',
        UPDATE_DATA_SUCCESS: 'UPDATE_DATA_SUCCESS',
    },
    CHANGE_LOADER_STATE: 'CHANGE_LOADER_STATE',
    CHANGE_TOAST_STATE: 'CHANGE_TOAST_STATE',
    UPDATE_TOKEN: 'UPDATE_TOKEN',
};
