export default {
    common: {
        CHANGE_LOADER_STATE: 'CHANGE_LOADER_STATE',
        CHANGE_TOAST_STATE: 'CHANGE_TOAST_STATE',
        CHANGE_MODAL_STATE: 'CHANGE_MODAL_STATE',
    },
    user: {
        UPDATE_TOKEN: 'UPDATE_TOKEN',
        UPDATE_PROFILE: 'UPDATE_PROFILE',
        LOGOUT: 'LOGOUT',
        UPDATE_COMPANY: 'UPDATE_COMPANY',
    },
    employees: {
        UPDATE_EMPLOYEES: 'UPDATE_EMPLOYEES',
        UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    },
    template: {
        UPDATE_TEMPLATES: 'UPDATE_TEMPLATES',
    },
};
