export default {
    home: {
        "UPDATE_DATA_REQUESTED": "UPDATE_DATA_REQUESTED",
        "UPDATE_DATA_FAILURE": "UPDATE_DATA_FAILURE",
        "UPDATE_DATA_SUCCESS": "UPDATE_DATA_SUCCESS",
    }
}